name: linux-clang-x86

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-clang-x86:
    runs-on: arch

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build -S ${{github.workspace}}/src -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: ${{github.workspace}}/build/test/el_test
