name: linux-gcc-x86

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  #BUILD_TYPE: Debug

jobs:
  linux-gcc-x86:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Ninja
      run: sudo apt install ninja-build

    - name: Configure CMake
      #run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      run: cmake -G Ninja -B ${{github.workspace}}/build -S ${{github.workspace}}/src -DGCC_DEBUG=1

    - name: Build
      #run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      run: cmake --build ${{github.workspace}}/build
        
    - name: Configure Test
      run: cmake -G Ninja -B ${{github.workspace}}/build -S ${{github.workspace}}/src -DGCC_DEBUG=1 -DBUILD_TEST=1

    - name: Build Test
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: ${{github.workspace}}/build/test/test
