name: linux-clang-x86

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  #BUILD_TYPE: Debug

jobs:
  linux-clang-x86:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Clang
      run: sudo apt install clang

    - name: Configure CMake
      #run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}/src -DGCC_DEBUG=1
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++

    - name: Build
      #run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      run: make -C ${{github.workspace}}/build

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}
      
